name: Release

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  pure-python-wheel-and-sdist:
    name: Build a pure Python wheel and source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all tags
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/*
          if-no-files-found: error

  publish-pypi:
    name: Publish package to PyPI
    needs:
      - pure-python-wheel-and-sdist
    runs-on: ubuntu-latest
    environment:
      name: release
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: dist

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Publish built artifacts to PyPI
        run: uv publish --trusted-publishing always
